# AddVolume completion

# Generated by gompletely (https://github.com/miekg/gompletely)

_AddVolume_completions_filter() {
  local words="$1"
  local cur=${COMP_WORDS[COMP_CWORD]}
  local result=()

  if [[ "${cur:0:1}" == "-" ]]; then
    echo "$words"

  else
    for word in $words; do
      [[ "${word:0:1}" != "-" ]] && result+=("$word")
    done

    echo "${result[*]}"

  fi
}

_AddVolume_completions() {
  local cur=${COMP_WORDS[COMP_CWORD]}
  local compwords=("${COMP_WORDS[@]:1:$COMP_CWORD-1}")
  local compline="${compwords[*]}"

case "$compline" in

  *'--volume-type')
	while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_AddVolume_completions_filter "vol srvvol home localhome")" -- "$cur")
      ;;

  *'--readonly-group')
	while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_AddVolume_completions_filter "$(c group list --comp)")" -- "$cur")
      ;;

  *'--protogroup')
	while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_AddVolume_completions_filter "$(c protogrp list --comp)")" -- "$cur")
      ;;

  *'--home')
	while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_AddVolume_completions_filter "$(c user list --comp)")" -- "$cur")
      ;;

  *'--fs-type')
	while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_AddVolume_completions_filter "zfs lvm dir")" -- "$cur")
      ;;

  'list'*)
	while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_AddVolume_completions_filter "hoi blaa")" -- "$cur")
      ;;

  *)
	while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen  -A file-W "$(_AddVolume_completions_filter "--setup --home --protogroup --force-home --fs-type --readonly-group --volume-type --mail-contact $(c volume-server list --comp) $(c group list --comp)")" -- "$cur")
      ;;

  esac
} &&
complete -F _AddVolume_completions AddVolume