# AddVolume completion                                     -*- shell-script -*-

# This bash completions script was generated by
# completely (https://github.com/dannyben/completely)
# Modifying it manually is not recommended

_AddVolume_completions_filter() {
  local words="$1"
  local cur=${COMP_WORDS[COMP_CWORD]}
  local result=()

  if [[ "${cur:0:1}" == "-" ]]; then
    echo "$words"

  else
    for word in $words; do
      [[ "${word:0:1}" != "-" ]] && result+=("$word")
    done

    echo "${result[*]}"

  fi
}

# In the default below we add a check where in the completion are you=, which ARGUMENT (not an option) and output the completion
# for that thing.


_AddVolume_completions() {
  echo ${COMP_WORDS[@]}
  local cur=${COMP_WORDS[COMP_CWORD]}
  local compwords=("${COMP_WORDS[@]:1:$COMP_CWORD-1}")
  local compline="${compwords[*]}"

  echo "CL" $compline "CL" >&2
  echo "CW" $compwords "CW" >&2
  echo "CUR" $cur "CUR" >&2

  case "$compline" in
    *'--readonly-group')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_AddVolume_completions_filter "$(c group list --comp)")" -- "$cur")
      ;;

    *'--volume-type')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_AddVolume_completions_filter "vol srvvol home localhome")" -- "$cur")
      ;;

    *'--protogroup')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_AddVolume_completions_filter "$(c protogrp list --comp)")" -- "$cur")
      ;;

    *'--fs-type')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_AddVolume_completions_filter "zfs lvm dir")" -- "$cur")
      ;;

    *'--home')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_AddVolume_completions_filter "$(c user list --comp)")" -- "$cur")
      ;;

    *)
                 # determine positional argument count
                COMP_CARG=$COMP_CWORD
                for i in "${COMP_WORDS[@]}"; do
                        [[ ${i} == -* ]] && ((COMP_CARG = COMP_CARG - 1))
                done
                echo "COMP_CARG" $COMP_CARG



      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -W "$(_AddVolume_completions_filter "--setup --home --protogroup --force-home --fs-type --readonly-group --volume-type --mail-contact $(c volume-server list --comp) $(c group list --comp)")" -- "$cur")
      ;;

  esac
} &&
  complete -F _AddVolume_completions AddVolume

# ex: filetype=sh
